"on":
  push:
    branches:
    - deploy
name: Deploy to qwee
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply
      env:
        PORTER_CLUSTER: "1856"
        PORTER_DEPLOYMENT_TARGET_ID: 0c6e9823-f193-4e00-90ec-c9a4c1b144c2
        PORTER_HOST: https://cloud.porter.run
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "1969"
        PORTER_REPO_NAME: ${{ github.event.repository.name }}
        PORTER_STACK_NAME: qwee
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1969_1856 }}
